media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: "{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
      - name: category
        label: Category
        type: string
      - name: author
        type: object
        fields: 
          - name: name
            type: string
          - name: role
            type: string
            default: ""
      - name: date
        type: date
        default: ""
        options:
          time: false
          format: yyyy-MM-dd
      - name: excerpt
        label: Excerpt
        type: string
        required: true
        default: ""
      - name: featured
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text